urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns('',

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    url(r'^people/', include('mezzanine_people.urls')),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))
    

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

books/models.py
from django.db import models

# Create your models here.
from mezzanine.pages.models import Page
from mezzanine.generic.fields import KeywordsField
from mezzanine.generic.fields import CommentsField
from mezzanine.generic.fields import RatingField

# The members of Page will be inherited by the Author model, such
# as title, slug, etc. For authors we can use the title field to
# store the author's name. For our model definition, we just add
# any extra fields that aren't part of the Page model, in this
# case, date of birth.

class Author(Page):
    dob = models.DateField("Date of birth")
    comments = CommentsField()
    rating = RatingField()

class Book(models.Model):
    author = models.ForeignKey("Author")
    cover = models.ImageField(upload_to="authors")
    keywords = KeywordsField()

moderna/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render

# Create your views here.

books/templates/pages/author.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n future staticfiles %}
{% load rating_tags %}
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
<link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
{% endifinstalled %}

{% compress css %}
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/rtl.css" %}">
{% endif %}
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{% static "css/cartridge.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
{% endif %}
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}

{% compress js %}
<script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-extras.js" %}"></script>
{% block extra_js %}{% endblock %}
{% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">{% trans "Toggle Navigation" %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
    {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %}
</div>
<div class="navbar-collapse collapse">
    {% search_form "all" %}
    {% page_menu "pages/menus/dropdown.html" %}
</div>
</div>
</div>

<div class="container">

{% nevercache %}
{% if messages %}
<div class="messages">
{% for message in messages %}
<div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}
</div>
{% endfor %}
</div>
{% endif %}
{% endnevercache %}

<h1>{% block title %}{% endblock %}</h1>

<ul class="breadcrumb">
{% spaceless %}
{% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
{% endspaceless %}
</ul>

</div>

<div class="container">
<div class="row">

<div class="col-md-2 left">
    {% block left_panel %}
    <div class="panel panel-default tree">{% page_menu "pages/menus/tree.html" %}</div>
    {% endblock %}
</div>

<div class="col-md-7 middle">
    {% block main %}{% endblock %}
    <h1>{{ page.author.title }}</h1>
xxxx3
<p>{{ page.author.dob }}</p>
{% for book in page.author.book_set.all %}
<img src="{{ MEDIA_URL }}{{ book.cover }}">
{% endfor %}


{% load comment_tags %}

<h3>There are {{ page.author.comments_count }} comment{{ page.author.comments_count|pluralize }}</h3>
{% comments_for page.author %}

{% rating_for page.author %}





</div>

<div class="col-md-3 right">
    {% nevercache %}
    {% include "includes/user_panel.html" %}
    {% endnevercache %}
    <div class="panel panel-default">
    <div class="panel-body">
    {% block right_panel %}
    {% ifinstalled mezzanine.twitter %}
    {% include "twitter/tweets.html" %}
    {% endifinstalled %}
    {% endblock %}
    </div>
    </div>
</div>

</div>
</div>



<footer>
<div class="container">
{% page_menu "pages/menus/footer.html" %}

<div class="row">
<p class="site-info text-center">
    {% trans "Powered by" %}
    <a class="patata" href="http://mezzanine.jupo.org">Mezzanine2</a>{% ifinstalled cartridge.shop %},
    <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}
    {% trans "and" %}
    <a href="http://www.djangoproject.com">Django</a>
    <span class="separator">|</span>
    {% trans "Theme by" %} <a target="_blank" href="http://getbootstrap.com">Bootstrap</a>
    {% ifinstalled mezzanine.mobile %}
    <span class="separator">|</span>
    <a href="{% url "set_device" "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>
    {% endifinstalled %}
</p>
</div>
</div>
</footer>

{% include "includes/footer_scripts.html" %}

</body>
</html>

books/templates/pages/author_old.html
<h1>{{ page.author.title }}</h1>
xxxx3
<p>{{ page.author.dob }}</p>
{% for book in page.author.book_set.all %}
<img src="{{ MEDIA_URL }}{{ book.cover }}">
{% endfor %}

moderna/templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n future staticfiles %}

<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
<link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
{% endifinstalled %}

{% compress css %}
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/fancybox/jquery.fancybox.css" %}">

<link rel="stylesheet" href="{% static "css/flexslider.css" %}">

<link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
<link rel="stylesheet" href="{% static "css/style.css" %}">

<link rel="stylesheet" href="{% static "skins/default.css" %}">





{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/rtl.css" %}">
{% endif %}
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{% static "css/cartridge.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
{% endif %}
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}

{% compress js %}
<script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-extras.js" %}"></script>
{% block extra_js %}{% endblock %}
{% include "includes/footer_scripts.html" %}
{% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">
<div id="wrapper">
	<header>
<div class="navbar navbar-default navbar-static-top" role="navigation">
<div class="container">
<div class="navbar-header">
   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
  {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
    
</div>
<div class="navbar-collapse collapse">
       {% page_menu "pages/menus/dropdown.html" %}
</div>
</div>
</div>
	</header>
{% block all_content %}
<div class="container">

{% nevercache %}
{% if messages %}
<div class="messages">
{% for message in messages %}
<div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}
</div>
{% endfor %}
</div>
{% endif %}
{% endnevercache %}


</div>
{% block breadcrumb_wrapper %}
<section id="inner-headline">
<div class="container">
	<div class="row">
		<div class="col-lg-12">
<ul class="breadcrumb">
{% spaceless %}
{% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
{% endspaceless %}
</ul>
</div>
</div>
</div>
</section>
{% endblock %}
{% block title_wrapper %}
<section class="callaction">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="big-cta">
					<div class="cta-text">
					<h2>{% block title %}{% endblock %}</h2>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}
<section id="{% block section_id %}content{% endblock %}">
<div class="container">
<div class="row">
{% block left_wrapper %}
	<div class="col-md-{% block left_col_size %}2{% endblock %} {% block left_class %}left{% endblock %}">
		{% block left_panel %}
		<div class="panel panel-default tree">{% page_menu "pages/menus/tree.html" %}</div>
		{% endblock %}
	</div>
{% endblock %}
{% block main_wrapper %}

<div class="col-md-{% block main_col_size %}7{% endblock %} {% block main_class %}middle{% endblock %}">
    {% block main %}{% endblock %}
</div>
{% endblock %}

{% block right_wrapper %}

<div class="col-md-{% block right_col_size %}3{% endblock %} {% block right_class %}right{% endblock %}">
    {% nevercache %}
    {% include "includes/user_panel.html" %}
    {% endnevercache %}
	<aside class="right-sidebar">
   
    {% block right_panel %}
    {% ifinstalled mezzanine.twitter %}
    {% include "twitter/tweets.html" %}
    {% endifinstalled %}
    {% endblock %}
    
	</aside>
</div>
{% endblock %}
</div>
</div>
</section>
{% endblock %}
<footer>
<div class="container">
{% page_menu "pages/menus/footer.html" %}
<div id="sub-footer">
<div class="row">
<div class="col-lg-6">
					<div class="copyright">
						<p>
							<span>Template by </span><a target="_blank" href="http://bootstraptaste.com">Bootstraptaste</a>. Mezzanine theme by <a target="_blank" href="http://thecodinghouse.in">CodingHouse</a>
						</p>
					</div>
				</div>
				<div class="col-lg-6">
					<ul class="social-network">
						<li><a title="" data-placement="top" href="#" data-original-title="Facebook"><i class="fa fa-facebook"></i></a></li>
						<li><a title="" data-placement="top" href="#" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></li>
						<li><a title="" data-placement="top" href="#" data-original-title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
						<li><a title="" data-placement="top" href="#" data-original-title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
						<li><a title="" data-placement="top" href="#" data-original-title="Google plus"><i class="fa fa-google-plus"></i></a></li>
					</ul>
				</div>
		

</div>
</div>
</div>
</footer>
</div>
{% compress js %}

<script src="{% static "js/jquery.easing.1.3.js"%}"></script>

<script src="{% static "js/jquery.fancybox.pack.js"%}"></script>
<script src="{% static "js/jquery.fancybox-media.js"%}"></script>
<script src="{% static "js/google-code-prettify/prettify.js"%}"></script>
<script src="{% static "js/portfolio/jquery.quicksand.js"%}"></script>
<script src="{% static "js/portfolio/setting.js"%}"></script>
<script src="{% static "js/jquery.flexslider.js"%}"></script>
<script src="{% static "js/animate.js"%}"></script>
<script src="{% static "js/custom.js"%}"></script>
{% endcompress %}

</body>
</html>

moderna/templates/blog/blog_post_detail.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n future disqus_tags %}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for blog_post as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}

{% endblock %}

{% block main %}

	{% block blog_post_main%}
		{{ block.super }}
		
		{% block blog_post_list_post_content %}
			
		{% endblock %}
		{% block blog_post_detail_content %}
		{% editable blog_post.content %}
		{{ blog_post.content|richtext_filters|safe }}
		{% endeditable %}
		{% endblock %}
		
		{% block read_more%}
		{% endblock %}
	{% endblock %}	

{% block blog_post_detail_keywords %}
{% keywords_for blog_post as tags %}
{% if tags %}
{% spaceless %}
<ul class="list-inline tags">
    <li>{% trans "Tags" %}:</li>
    {% for tag in tags %}
    <li><a href="{% url "blog_post_list_tag" tag.slug %}">{{ tag }}</a></li>
    {% endfor %}
</ul>
{% endspaceless %}
{% endif %}
{% endblock %}

{% block blog_post_detail_rating %}
<div class="panel panel-default rating">
    <div class="panel-body">
    {% rating_for blog_post %}
    </div>
</div>
{% endblock %}

{% block blog_post_detail_sharebuttons %}
{% set_short_url_for blog_post %}

<div class="bottom-article">
		<ul class="meta-post">
		<li>Share</li>
		<li><a class="" target="_blank" href="http://twitter.com/home?status={{ blog_post.short_url|urlencode }}%20{{ blog_post.title|urlencode }}"><strong><i class="fa fa-twitter"></i> </strong></a></li>
		<li><a class="" target="_blank" href="http://facebook.com/sharer.php?u={{ request.build_absolute_uri }}&amp;t={{ blog_post.title|urlencode }}"><i class="fa fa-facebook"></i></a>

		</ul>
		
	</div>


{% endblock %}

{% block blog_post_previous_next %}
<ul class="pager">
{% with blog_post.get_previous_by_publish_date as previous %}
{% if previous %}
<li class="previous">
    <a href="{{ previous.get_absolute_url }}"><i class="fa fa-arrow-left"></i> {{ previous }}</a>
</li>
{% endif %}
{% endwith %}
{% with blog_post.get_next_by_publish_date as next %}
{% if next %}
<li class="next">
    <a href="{{ next.get_absolute_url }}">{{ next }} <i class="fa fa-arrow-right"></i>
{% endif %}
{% endwith %}
</ul>
{% endblock %}

{% block blog_post_detail_related_posts %}
{% if blog_post.related_posts.all %}
<div id="related-posts">
<h3>{% trans 'Related posts' %}</h3>
<ul class="list-unstyled">
{% for post in blog_post.related_posts.all %}
     <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>
</div>
{% endif %}
{% endblock %}

{% block blog_post_detail_comments %}
{% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}
{% endblock %}

{% endblock %}

moderna/templates/blog/blog_post_list.html
{% extends "base.html" %}
{% load i18n future mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Blog" %}{% endif %}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title_wrapper %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
{% if tag or category or year or month or author %}
<li>{% spaceless %}
{% if tag %}
    {% trans "Tag:" %} {{ tag }}
{% else %}{% if category %}
    {% trans "Category:" %} {{ category }}
{% else %}{% if year or month %}
    {% if month %}{{ month }}, {% endif %}{{ year }}
{% else %}{% if author %}
    {% trans "Author:" %} {{ author.get_full_name|default:author.username }}
{% endif %}{% endif %}{% endif %}{% endif %}
{% endspaceless %}
</li>
{% endif %}
{% endblock %}

{% block left_wrapper %}
{% endblock %}
<div class="col-md-{% block main_col_size %}8{% endblock %}">
{% block main %}

{% if tag or category or year or month or author %}
    {% block blog_post_list_filterinfo %}
    <p>
    {% if tag %}
        {% trans "Viewing posts tagged" %} {{ tag }}
    {% else %}{% if category %}
        {% trans "Viewing posts for the category" %} {{ category }}
    {% else %}{% if year or month %}
        {% trans "Viewing posts from" %} {% if month %}{{ month }}, {% endif %}
        {{ year }}
    {% else %}{% if author %}
        {% trans "Viewing posts by" %}
        {{ author.get_full_name|default:author.username }}
    {% endif %}{% endif %}{% endif %}{% endif %}
    {% endblock %}
    </p>
{% else %}
    {% if page %}
    {% block blog_post_list_pagecontent %}
    {% if page.get_content_model.content %}
        {% editable page.get_content_model.content %}
        {{ page.get_content_model.content|richtext_filters|safe }}
        {% endeditable %}
    {% endif %}
    {% endblock %}
    {% endif %}
{% endif %}

{% for blog_post in blog_posts.object_list %}
	{% block blog_post_main%}	
	<article>
	<div class="post-image">
			<div class="post-heading">
			{% block blog_post_list_post_title %}
			{% editable blog_post.title %}
			<h3><a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a></h3>
			{% endeditable %}
			{% endblock %}
			</div>
			{% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
			{% block blog_post_list_post_featured_image %}
			<a href="{{ blog_post.get_absolute_url }}">
				<img class="" src="{{ MEDIA_URL }}{{blog_post.featured_image}}">
			</a>
			{% endblock %}
			{% endif %}
			
	</div>

{% block blog_post_list_post_content %}
{% editable blog_post.content %}
{{ blog_post.description_from_content|safe }}
{% endeditable %}
{% endblock %}
    <div class="bottom-article">
		{% block blog_post_list_post_metainfo %}
		{% editable blog_post.publish_date %}
		<ul class="meta-post">
		<li><i class="icon-calendar"></i><a href="#"> {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}</a></li>
		{% with blog_post.user as author %}
		<li><i class="icon-user"></i><a href="{% url "blog_post_list_author" author %}"> {{author.get_full_name|default:author.username}}</a></li>
		{% endwith %}
		
		{% with blog_post.categories.all as categories %}
			{% if categories %}
			<li><i class="icon-folder-open"></i>
    		{% for category in categories %}
			<a href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %}, {% endif %}
			{% endfor %}
			</li>
			{% endif %}
			{% endwith %}
			{% if blog_post.allow_comments %}
    
			{% if settings.COMMENTS_DISQUS_SHORTNAME %}
			<li>
			<i class="icon-comments"></i>
			<a href="{{ blog_post.get_absolute_url }}#disqus_thread"
				data-disqus-identifier="{% disqus_id_for blog_post %}">
				{% trans "Comments" %}
			</a>
			{% else %}
			<a href="{{ blog_post.get_absolute_url }}#comments">
			{% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
			</a>
			{% endif %}
			</li>
			{% endif %}
		
		</ul>
			{% block read_more%}
			<a class="pull-right" href="{{ blog_post.get_absolute_url }}">Continue reading <i class="icon-angle-right"></i></a>
			{% endblock %}
		{% endeditable %}
		{% endblock %}
	</div>

	</article>
     {% endblock %}
{% endfor %}

{% pagination_for blog_posts %}

{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_counts.html" %}
{% endif %}

{% endblock %}

</div><!-- END MAIN -->

<div class="col-md-{% block right_col_size %}4{% endblock %}">
{% block right_panel %}
{% include "blog/includes/filter_panel.html" %}
{% endblock %}
</div>

moderna/templates/generic/includes/disqus_sso.html
<script>
var disqus_config = function () {
    this.page.remote_auth_s3 = '{{ sso_data }}';
    this.page.api_key = '{{ public_key }}';
}
</script>